---
- name: Deploy to Tomcat Server
  hosts: web
  become: true
  become_method: sudo
  vars:
     local_warfile: /tmp/workspace/target/WebApp.war
     remote_webapps: /opt/apache-tomcat-9.0.65/webapps/WebApp.war

  tasks:
    - name: tomcat stop
      shell: /opt/apache-tomcat-9.0.65/bin/shutdown.sh

    - name: delete war directories in tomcat webapps
      file: path=/opt/apache-tomcat-9.0.65/webapps/WebApp.war state=absent

    - name: delete war file in tomcat webapps
      file: path=/opt/apache-tomcat-9.0.65/webapps/WebApp state=absent

    - name: copy war file
      copy:
        src: "{{ local_warfile }}"
        dest: "{{ remote_webapps }}"
        mode: 0777
      notify: start tomcat

  handlers:
    - name: start tomcat
      shell: /opt/apache-tomcat-9.0.65/bin/startup.sh