- name: Git pull maven compile
  hosts: jenkins
  become: true
  become_user: root
  
  tasks:
    - name: Create a workspace Directory
      file:
        path: /tmp/workspace
        owner: ubuntu
        group: ubuntu
        mode: 777
        recurse: yes 

    - name: check out the repository
      git: 
        repo: https://github.com/natacha-lafontaine/Project3---Ansible.git 
        dest: "/tmp/workspace"
        accept_hostkey: yes

    - name: maven clean package
      command: mvn -f /tmp/workspace/pom.xml clean package
