- name: Git pull maven compile
  hosts: jenkins
  become: true
  become_method: sudo
  
  tasks:
    - name: check out the repository
      git: repo=https://github.com/natacha-lafontaine/Project3---Ansible.git accept_hostkey=yes

    - name: maven clean package
      command: mvn clean package
