---
- name: Install Tomcat
  hosts: web
  remote_user: ubuntu
  become: true
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes
 
    - name: Create a Tomcat User
      user:
        name: tomcat
 
    - name: Create a Tomcat Group
      group:
        name: tomcat
 
    - name: Install Java 11
      apt: 
        name: openjdk-11-jdk 
        state: present
 
    - name: Create a Tomcat Directory
      file:
        path: /opt/apache-tomcat-9.0.65
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
 
    - name: download & unarchive tomcat
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
        dest: /opt/apache-tomcat-9.0.65
        remote_src: yes
        extra_opts: [--strip-components=1]
 
    - name: Change ownership of tomcat directory
      file:
        path: /opt/apache-tomcat-9.0.65
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory 
 
    - name: Start and Enable Tomcat on sever
      service:
        name: tomcat
        state: started
        enabled: yes